### ISSUE TITLE
ERROR!!!!

### ISSUE THREAD

**Issue by yay-whyawhy** [mallik-amaan/bankmanagementsystem#1]
Sorry for that, I'm having a issue while using Osintgram could you plzzzz!!!! help me to solve this the error is:                                                   └──╼ #python3 main.py mizan_memes_confessions

Attempt to login...
Error parsing error response: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/abdullah/Downloads/Osintgram/venv/lib/python3.9/site-packages/instagram_private_api/client.py", line 523, in _call_api
    response = self.opener.open(req, timeout=self.timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abdullah/Downloads/Osintgram/main.py", line 121, in <module>
    api = Osintgram(args.id, args.file, args.json, args.command, args.output, args.cookies)
  File "/home/abdullah/Downloads/Osintgram/src/Osintgram.py", line 48, in __init__
    self.setTarget(target)
  File "/home/abdullah/Downloads/Osintgram/src/Osintgram.py", line 61, in setTarget
    self.following = self.check_following()
  File "/home/abdullah/Downloads/Osintgram/src/Osintgram.py", line 1159, in check_following
    return self.api._call_api(endpoint)['user_detail']['user']['friendship_status']['following']
  File "/home/abdullah/Downloads/Osintgram/venv/lib/python3.9/site-packages/instagram_private_api/client.py", line 527, in _call_api
    ErrorHandler.process(e, error_response)
  File "/home/abdullah/Downloads/Osintgram/venv/lib/python3.9/site-packages/instagram_private_api/errors.py", line 135, in process
    raise ClientError(error_msg, http_error.code, error_response)
instagram_private_api.errors.ClientError: Not Found
help!!!!

**Comment by yash6756** [comment]
I'm getting the same issue can anyone resolve it?

**Comment by yay-whyawhy** [comment]
yeah!!
